jonhoo/fantoccini

- README.md
- src/lib.rs
- Removed `#` from the use statements which unhides statements from generated README.md when you use `cargo readme > README.md`
> Unhide use statements for a more newb friendly doc

- src/lib.rs
If merged this will close https://github.com/jonhoo/fantoccini/issues/6.
---
Usage of `Element::select_by_value` is illustrated below:
```rust
fn select_product_type(c: Client) -> impl Future<Item = Client, Error = CmdError> {
c.find(Locator::Css("select[name='productType']"))
.and_then(|e| e.select_by_value("Dairy"))
}
```
> Implement dropdown option selection by value

- src/lib.rs
Explicitly mention that `return` has to be used in the execute method to retrieve the value of a variable.
> Explicitly mention how to get variable values with execute()

- src/lib.rs
I was looking for the [Element Send Keys method](https://www.w3.org/TR/webdriver/#element-send-keys) and couldn't find it, so I've added it in if you want it.
> Adds in method for sending keys

- src/session.rs
When trying to run `fantoccini` against a local `selenium-server` instance with the main example in the documentation (albeit at http://localhost:4444/wd/hub/ ), I'd see an error of the form: `First match w3c capabilities is zero length`. 
The spec at https://www.w3.org/TR/webdriver1/#processing-capabilities mentions that `firstMatch` capabilities must be non-empty if defined, so this PR makes that happen.
> Add default empty first-match capabilities.

- src/error.rs
- src/session.rs
The compiler produces a
> warning: trait objects without an explicit `dyn` are deprecated
as a result of the `warn(bare_trait_objects)` compiler message being enabled by default.
This commit simply accepts suggested syntax, using `dyn` in these three locations where warnings are produced. I assume these suggestions are what was already being done internally by the compiler.
> Resolve warning about deprecated trait objects without explicit `dyn`

- src/lib.rs
- src/session.rs
Implement the element clear command supported by webdriver
https://docs.rs/webdriver/0.39.0/src/webdriver/command.rs.html#270
https://w3c.github.io/webdriver/#element-clear
Basically renames the element click functionality
> add method for element clear command

- src/lib.rs
- src/session.rs
- tests/common.rs
For #55 - really simple first draft by now, as most of the actual functionality was already implemented, I just needed to add an interface for it. I've updated src/session.rs in the process to support the latest hyper master (they seem to have removed that parameter).
At first, I thought about passing an `&Element` to the `find_from`/`find_all_from` methods, but that would be difficult as the `Element`'s `find`/`find_from` methods must take `&mut self` to be able to call the inner `Client`, but by passing on `&self` into the `find_from` Future, they would also return an immutable borrow of self, so I went to just cloning the `Element`.
Two questions:
1. Should I remove the `#![feature(async_await)]` from lib.rs and tests/common.rs? As it's stabilized on nightly now, these raise a warning …
> Add initial support for FindElement(s)FromElement

- src/lib.rs
This improves Safari compatibility, as `safaridriver` on macOS returns an empty string instead of `about:blank` by default if querying a browser session that is not currently viewing a web page.
> Convert empty URL strings to "about:blank". Fixes jonhoo/fantoccini#60

- src/lib.rs
- tests/common.rs
- tests/redirect_test.html
The `wait_for_find(…)` method on `Client` was taking ownership of the client instance (used `mut self` in the signature instead of a mutable reference to self).
This just changes it to a mutable reference so that calling wait_for_find doesn't move the client.
> Improvements to `wait_<…>` functions

- src/error.rs
Printing a CmdError currently causes an infinite recursion, calling `<CmdError as Display>::fmt` over and over again until the stack inevitably overflows. This bug was introduced by https://github.com/jonhoo/fantoccini/commit/f05bd488d5dd0391003f61097843365145884730 . We basically undo this commit and add `#[allow(deprecated)]` instead. Those functions aren't going anywhere anyways, we're defining them ourselves!
> Fix stackoverflow when printing CmdError

- src/error.rs
- src/session.rs
- tests/local.rs
This can happen when a handle on an element is kept but the element is
not on the page anymore (e.g. because it was removed from the DOM or
because the browser navigated to another page).
https://www.w3.org/TR/webdriver/#dfn-stale-element-reference
Note that I reused the existing `NoSuchElement` error variant. Let me know if you would prefer a new `StaleElementReference` error variant instead.
> Support the "stale element reference" error from WebDriver

- tests/remote.rs
Wikipedia has changed its front page a little bit :smile: 
```
[zhiburt@zhiburt fantoccini]$ cargo test
Finished test [unoptimized + debuginfo] target(s) in 0.17s
Running target/debug/deps/fantoccini-9499f1d732885da8
running 1 test
test error::tests::ensure_display_error_doesnt_stackoverflow ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Running target/debug/deps/common-78b6b593c7eabae2
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Running target/debug/deps/local-0c98d2dd68f4ea31
running 22 tests
test chrome::double_close_window_test ... ok
test chrome::close_window_test ... ok
test chrome::find_and_click_link_test ... ok
test chrome::iframe_test ... ok
test chrome::new_tab_test ... ok
test …
```
> Fix tests finds_sub_elements, finds_sub_elements

- src/lib.rs
- src/session.rs
- tests/local.rs
Resolves #98 via the WebDriver `GetActiveElement` command.
This method is useful for example when interacting with a site that provides keyboard shortcuts.
> Add active_element method

- examples/basic_setup/Cargo.toml
- examples/basic_setup/src/main.rs
Update basic_setup example to use async await syntax
Background: Today I tried to figure out how to use fantoccini, and opened basic_setup example first. I was very confused to find old futures syntax. Hopefully after these changes, newcomers will not have this problem.
> Update basic_setup example to use async await syntax

- src/session.rs
If `geckodriver` is not started but we create a `Client` it will return error but also `panic`.
```
ERR: "webdriver server did not respond: error trying to connect: tcp connect error: Cannot assign requested address (os error 99)"
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fantoccini-0.14.0/src/session.rs:276:46
```
There was a bare testing so it may affect something.
Sorry if the PR is not correct from code perspective (which may be true)
> handle shutdown with not created session

- Cargo.toml
- tests/common.rs
As suggested by @jonhoo in https://github.com/jonhoo/fantoccini/issues/114#issuecomment-755096495 to upgrade faster to tokio 1.0 we could remove warp as a dependency.
The warp server gets replaced by a very simple hyper service. As I don't see a reason why test files could be of another type than html, I've hard coded that in. But this could be fixed quite easily if at any point in time that assumption changes.
Or I can edit the pull request to be more "generic" over the file type, but that would probably require another dependency.
I would be happy to hear some feedback, this is my first pull request ever.
> Replace the test warp server with hyper (remove warp as a dependency)

- Cargo.toml
- src/error.rs
- src/session.rs
- tests/common.rs
We still end up with an unused transitive dependency on tokio 0.2
through `webdriver`. Upstream has a pending fix for that in
https://bugzilla.mozilla.org/show_bug.cgi?id=1684226, but this is still
worthwhile to get out the door.
Fixes #114.
> Upgrade to tokio 1.0

- Cargo.toml
`webdriver 0.43` made the server aspects of the code optional
(https://bugzilla.mozilla.org/show_bug.cgi?id=1684226). We take
advantage of that to get rid of `webdriver`'s `warp` dependency which
brought in an old version of tokio.
This change is unfortunately backwards-incompatible because we publicly
expose types from the `webdriver` crate.
> Bump webdriver and remove server feature

- Cargo.toml
- tests/local.rs
- tests/remote.rs
`serial_test` since [0.3](https://github.com/palfrey/serial_test/releases/tag/v0.3.0) includes `serial_test_derive` and lets you use the macro without needing to directly include `serial_test_derive`
> Remove serial_test_derive dependency

- Cargo.toml
- src/client.rs
- src/elements.rs
- src/lib.rs
- src/session.rs
- tests/common.rs
- tests/remote.rs
The PR adds many more links to the WebDriver specification, tidies up
the features a little, re-organizes the big `src/lib.rs` into smaller
files, and splits up `impl` blocks (and `fn` order) to correspond to the
command order in the spec.
> Lots of freshening up

- src/client.rs
- src/session.rs
Added `WebDriverCommand::TakeElementScreenshot` via the `Client::screenshot_element()` method.
https://www.w3.org/TR/webdriver1/#dfn-take-element-screenshot
> Add support for the "take element screenshot" WebDriver command

- src/session.rs
Fixes #120.
As I wrote in the issue, the error occurred when `.goto()` was used on e.g. any URL redirecting to a download, which opens a download prompt (invisible when running headless), this seems to make geckodriver return with a timeout error because the "page" never loaded, i.e. the download. 
The error appeared after 5 minutes, which is exactly the default `pageLoad` timeout. After setting it to 5 seconds, it instead occurred *exactly* after 5 seconds. Based on this I believe this is the correct `ErrorStatus`, or at the very least this is better than dropping the connection without any ability to actually shutdown the still-alive session.
In any case, it works for me! One funny thing is that the download prompt remains forever instead of closing, but it keeps chugging along to the …
> Add error type for pageload timeout

- tests/common.rs
Both geckodriver and chromedriver pick the correct binary up automatically. Also, the current hardcoded path does not work on
Windows.
> Remove binary flag in test client

- Cargo.toml
- src/client.rs
- src/cookies.rs
- src/error.rs
- src/lib.rs
- src/session.rs
- tests/common.rs
- tests/remote.rs
This PR adds support for the cookie operations defined in [16. Cookies](https://www.w3.org/TR/webdriver1/#cookies) in the WebDriver spec. In particular, I've implemented the following operations:
* Get All Cookies
* Get Named Cookie
* Delete Cookie
* Delete All Cookies
The last operation, "Add Cookie", requires support from the `webdriver` crate.  The primary issue is that the `AddCookieParameters` struct does not implement `Serialize`, which means that we can't build the POST request on our side.  I'll be trying to get in touch with the geckodriver folks to see if this can be changed on their end.
* Added a new module, `cookies.rs`.  This module contains the cookie-related `Client` methods as well as a few functions for converting between raw JSON (from WebDriver) and `cookie::Cookie` …
> Add support for WebDriver cookie operations

- examples/basic.rs
- examples/wait.rs
- src/client.rs
- src/error.rs
- src/lib.rs
- src/wait.rs
- tests/remote.rs
This is first proposal for the following issues:
Fixes https://github.com/jonhoo/fantoccini/issues/81
Fixes https://github.com/jonhoo/fantoccini/issues/90
Fixes https://github.com/jonhoo/fantoccini/issues/27
I tried to:
* Avoid cloning the client
* Allow for future extensions on the wait parameters
* Provide a single non-opinionated "on" method
* Provide more opinionated function which make your live easier (on_element, on_predicate)
I didn't not async-trait, as it wasn't in the project already. Maybe that could help creating a better API.
One thing I wasn't able to achieve so far, is to provide a way directly pass in e.g. a `Locator` into the `on` method, and let it `Into` an appropriate function. I think that would be nice, but it also is a bit above my Rust future and lifetime …
> Implement "wait for" functions with a timeout

- Cargo.toml
- src/lib.rs
Properly updates to hyper-rustls 0.23, as #141 and #139 give errors when trying to compile with it.
Closes #141
> Upgrade hyper-rustls to 0.23

- Cargo.toml
Given that [`cookie` 0.16.0 has been released](https://github.com/SergioBenitez/cookie-rs/releases/tag/0.16.0), we may make a 0.18.0 release now.
> Prepare 0.18.0 release

- README.md
`try_concat` is no longer compatible with hyper's `Body` (see https://github.com/hyperium/hyper/issues/1951). I didn't use https://docs.rs/hyper/latest/hyper/body/fn.to_bytes.html as to not require a direct hyper dependency for the snippet.
> Use `try_fold` instead of `try_concat` in README

- README.md
- src/actions.rs
- src/client.rs
- src/cookies.rs
- src/elements.rs
- src/error.rs
- src/key.rs
- src/keys.rs
- src/lib.rs
- src/session.rs
- src/wd.rs
- tests/actions.rs
- tests/alert.rs
- tests/common.rs
- tests/elements.rs
- tests/local.rs
- tests/remote.rs
- tests/test_html/sample_page.html
I've wired up and implemented most of the remaining `WebDriverCommand`s.
Some points of discussion:
1. A lot of methods in `fantoccini` take `&mut self` when mutable access is not required. In fact most methods should be fine with `&self`. Is this intentional?
2. In order to wrap `Element` in `thirtyfour`, I needed to make its members public. Is this going to cause any issues?
3. It would be nice to re-export some of the types used by `fantoccini`, so that calling crates can import (use) the exact versions without having to try to keep things in lockstep. I've add a couple of re-exports under `fantoccini::external` but feel free to suggest a better namespace. I'd also be fine with these being behind a feature flag in order to not pollute the namespace.
4. I haven't yet added tests (except …
> Implement remaining WebDriver commands

- README.md
- examples/basic.rs
- examples/wait.rs
- src/client.rs
- src/cookies.rs
- src/elements.rs
- src/lib.rs
- src/session.rs
- src/wait.rs
- tests/actions.rs
- tests/alert.rs
- tests/common.rs
- tests/elements.rs
- tests/local.rs
- tests/remote.rs
This is intended firstly as a discussion point w.r.t. issue #153 and also to show how this would look with all of the mutability requirements minimized. 
The one method where I think capturing self might be warranted is `Client::close()`.
Perhaps its sig could be changed to:
```rust
pub async fn close(self) -> Result<Client, error::CmdError> {
```
Obviously all of this is a highly disruptive breaking change with many implications for calling code.
> Make access to self immutable where possible

- Cargo.toml
Since you're going to release a minor version anyway I wouldn't mind having the ability to reduce `hyper`'s dependencies.
---
Makes the `http2` feature optional and enables it by default.
> Disable the hyper http2 feature

- tests/remote.rs
This is why local tests are nice.
Should unblock #167.
> The portal headings are no longer h3

- Cargo.toml
- src/actions.rs
- src/cookies.rs
This PR updates `webdriver` to the latest version and makes the required adjustments for it to compile. I have not tested this locally since I'm unable to get `geckodriver` working, so I'm relying on CI to catch if some of these fields need filled out more.
Supersedes #173
> Update webdriver to 0.46

- src/session.rs
Fixes: #180
BrowserStack (selenium v >=4) requires the charset to be set due to some
undisclosed security vulnerability, despite technically being implied by
the JSON spec.
Adding `charset=utf-8` should not have any backward compatibility issues
with current users.
> Add `charset=utf-8` to session `Content-Type` header

- src/elements.rs
- src/error.rs
- src/session.rs
- src/wait.rs
- tests/actions.rs
- tests/alert.rs
- tests/local.rs
- Add `ErrorStatus` enum
- Remove `webdriver::error::WebDriverError`
- Use `error::WebDriver` directly to avoid double-handling
NOTE: `StaleElementReference` is no longer combined with `NoSuchElement`.
I essentially copied the `ErrorStatus` enum from the webdriver crate, noting that the majority of the comments are public documentation from the WebDriver spec. Do we need to remove the comments that are not in the spec? I'm not sure what the MPL license requirements are.
Ideally I'd like to move the `NoSuchElement` etc. variants back into the `CmdError::Standard` variant - not sure how you feel about that. That would break almost every application using this crate :( 
Otherwise there may be confusion about those variants existing in `ErrorStatus` but they can never be captured that way. …
> Add ErrorStatus enum and remove webdriver::error::WebDriverError

- examples/basic.rs
This is a simple fix to resolve the "Run" button locator issue in the example file.
> Fix example basic run button locator

- src/cookies.rs
- tests/remote.rs
Fetching all cookies from fantoccini client and loading them back reveals that same_site is not properly parsed when converting from Cookie -> WebDriverCookie.
For example, client.get_all_cookies() can return both the following same_site values in different cookies, the second of which is transformed by the map call into an Option::None which gets ignored by WebDriverCookie serde skip_serializing_if = "Option::is_none":
same_site: Some(
None,
),
same_site: None,
An example error when calling client.add_cookie() with the above "same_site: None":
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Standard(WebDriver { error: InvalidArgument, message: "invalid argument: invalid 'sameSite'\n
(Session info: chrome=98.0.4758.80)"
This fixes the error by parsing the top-level …
> Fix Cookie -> WebDriverCookie same_site parsing

- src/session.rs
Previously, the print command would default to using a GET, and not forwarding its parameters, but was otherwise implemented with the correct path.
I have tested that this does fix the issue, can add a test if you want as well
> Fully implement the print command

- Cargo.lock
- Cargo.toml
This PR is similar to https://github.com/jonhoo/fantoccini/pull/142 and updates `hyper-rustls` to the latest version to stay in sync with the rest of the `rustls` ecosystem.
Additionally, I made a small change to how the `openssl` dependency was being specified. As it was, it was forcing any user of the  `fantoccini` crate to depend on `openssl` even if you weren't using the `native-tls` feature.
> Update hyper-rustls to 0.24

- tests/local.rs
- tests/remote.rs
- tests/test_html/redirect_test.html
This PR removes Wikipedia as a dependency for the `wait_for_navigation` test, it also moves `redirect_test.html` in with the other HTML test documents.
Thanks.
Chase
> Migrate wait_for_nav test to use local files

- src/lib.rs
This note seems outdated so here it's removed.
> examples don't seem to use panic! or unwrap anymore

- examples/basic.rs
Looks like the Rust playground changed their HTML.
> Fix XPath to 'Run' button in basic example

- src/lib.rs
The old URL shows a generic 404 error: "Site not found".
> Move the `goog:chromeOptions` to a new URL

- Cargo.lock
- Cargo.toml
Prior to hyper 1 bump merging in https://github.com/jonhoo/fantoccini/pull/245, which will be a bigger breaking change.
> Bump and release rc.7 as 0.20.0

- ci/windows-latest-chrome.ps1
- tests/common.rs
after the stream on the July 14th I tried to dig into why windows selenium is not happy
I don't understand it really but these flags work everywhere on CI, the old flags would fail pretty much every time otherwise
> chromedriver flags that make ci happy eveywhere

- README.md
From the README I'm guessing that Method used to be re-exported by fantoccini; that's not the case in the current code. Fixed it to explicitly refer to http::Method.
> README: fix Method type

- Cargo.lock
No need to bump Cargo.toml in Rust.
Closes #262
> Bump openssl for dependabot

- src/client.rs
Closes #148 
This PR introduces a `RawRequestBuilder` struct to handle raw HTTP requests with optional cookie handling.
_Builder Pattern Implementation:_
- `RawRequestBuilder` for setting HTTP method `(method)`, URL `(url)`, optional cookie URL `(cookie_url)`, request modification function `(map_request)`, and sending the request `(send)`.
-  Added `raw_request` method to the Client struct to initialize the `RawRequestBuilder`.
> feat(client): Implement `RawRequestBuilder` for raw HTTP requests

- src/error.rs
- src/session.rs
Closes #175 
Added `UnexpectedError(CmdError)` variant to handle errors from the webdriver host that do not conform to the expected standard.
> fix(session): Add `UnexpectedError(CmdError)` variant

- src/client.rs
- src/session.rs
Closes #57   
The `with_existing_session` method introduces the ability to reconnect to an already established WebDriver session using its `session ID`. This enables reuse of an active session without having to create a new one, which is particularly beneficial in scenarios such as process restarts or unexpected disconnections.
> feat: Add reconnection capability for persisted WebDriver sessions

- src/client.rs
This change ensures that we issue a new session when we create a new client.
Close #281
> fix(client): new_with_connector: correctly setup session

- src/client.rs
I've also marked `.map_request` as `#[must_use]` so that failing to use the re-mapped builder gets a warning from the compiler.
Fixes #290.
> Actually apply `before` in `with_raw_client_for`

- Cargo.lock
Runs `cargo update` using the MSRV aware resolver. This unbreaks CI while we wait for #294.
```
❯ cargo update --verbose
Updating crates.io index
Locking 140 packages to latest Rust 1.67.0 compatible versions
Updating addr2line v0.22.0 -> v0.24.2
Removing adler v1.0.2
Adding adler2 v2.0.0
Updating autocfg v1.3.0 -> v1.4.0
Updating aws-lc-rs v1.8.1 -> v1.13.1
Updating aws-lc-sys v0.20.1 -> v0.29.0
Updating backtrace v0.3.73 -> v0.3.74 (available: v0.3.75, requires Rust 1.82.0)
Updating bindgen v0.69.4 -> v0.69.5
Updating bitflags v2.6.0 -> v2.9.1
Updating bytes v1.7.1 -> v1.10.1
Updating cc v1.1.15 -> v1.2.26
Updating cmake v0.1.51 -> v0.1.54
Adding displaydoc v0.2.5
Updating either v1.13.0 -> v1.15.0
Updating errno v0.3.9 -> v0.3.12
Updating fastrand v2.1.1 -> v2.3.0
Updating futures …
```
> build(deps): upgrade semver compatible dependencies

- src/print.rs
This fixes the A4 paper size const definition in the printsize struct, where the width and height values were inverted
> printsize (fix): swap const width and height for A4

- .github/workflows/check.yml
- Cargo.lock
- Cargo.toml
- ci/windows-latest-firefox.ps1
- src/actions.rs
- src/client.rs
- src/elements.rs
- src/session.rs
- tests/actions.rs
Breaking change because the webdriver crate now generates floating point numbers for pointer move operations, which are rejected by older versions of Chrome and Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1959464 for details.
> cargo update
